### ISSUE TITLE
Base64 encoded pdf content in API request

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-static-pdf#1]
I started to use this format for sending base64 encoded content instead of the referenced asset.

https://github.com/jsreport/jsreport-pdf-sign/blob/master/test/pdfSignTest.js#L116
```js
reporter.render({
      template: {
        content: 'Hello',
        engine: 'none',
        recipe: 'chrome-pdf',
        pdfSign: {
          certificateAsset: {
            content: fs.readFileSync(path.join(__dirname, 'certificate.p12')).toString('base64'),
            encoding: 'base64',         
          }
        }
 })
```

The same is [here](https://github.com/jsreport/jsreport-docxtemplater/blob/master/lib/recipe.js#L25) in the docxtemplater. 
It sounds this will be occurring quite often in our API so it would be better to unite it.

@bjrmatos What you think?

**Comment by bjrmatos** [comment]
done as part of `0.2.0` and the `encoding` property is required instead of setting some default
